[package]
name = "abalone"
version = "0.1.0"
edition = "2021"

[dependencies]
abalone_core = { workspace = true }
egui = { version = "0.23.0", features = ["persistence"] }
eframe = { version = "0.23.0", features = ["persistence"] }
serde = { workspace = true }
serde_derive = { workspace = true }
