[workspace]
resolver = "2"
members = [
    "core",
    "client",
    "server",
]

[workspace.dependencies]
abalone_core = { path = "core" }
serde = { version = "1.0", features = ["serde_derive"] }
serde_derive = "1.0"
